[package]
name = "index"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"

layout = { path = "../layout" }
sugar = { path = "../sugar" }
system = { path = "../system" }
