[package]
name = "life"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"

[dependencies.web-sys]
version = "0.3.77"
features = [
  "CanvasRenderingContext2d",
  "Document",
  "DomTokenList",
  "HtmlCanvasElement",
  "HtmlElement",
  "Node",
  "Text",
  "Window",
  "console",
]
