[package]
name = "perf"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"

sugar = { path = "../sugar" }
system = { path = "../system" }

[dependencies.web-sys]
version = "0.3.77"
default-features = false
features = ["Document", "Element", "Performance", "Window"]
