[package]
name = "sugar"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"

system = { path = "../system" }

[dependencies.web-sys]
version = "0.3.77"
features = ["Element"]
